-- BELOW IS A PROCEDURE USED TO MERGE DATA TO A MASTER LOOKUP TABLE, INCLUDING CTE'S AND JOINS


--DROP PROCEDURE GENERAL_HOSPITAL_PATIENTS.MERGE_DATA_TO_PATIENT_MASTER_TABLE();
CREATE PROCEDURE IF NOT EXISTS GENERAL_HOSPITAL_PATIENTS.MERGE_DATA_TO_PATIENT_MASTER_TABLE()
RETURNS STRING
LANGUAGE SQL
AS
$$

DECLARE

    base_table STRING DEFAULT 'GENERAL_HOSPITAL_PATIENTS.MASTER_PATIENT_LOOKUP_LOAD';
    datestamp STRING DEFAULT (SELECT TO_VARCHAR(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()), 'YYYYMMDD'));
    failover_table STRING DEFAULT '' || base_table || '_' || datestamp || '';
    create_failover_table STRING DEFAULT 'CREATE TABLE IF NOT EXISTS ' || :failover_table || ' AS SELECT * FROM ' || :base_table || ';';

BEGIN

    CREATE OR REPLACE TEMPORARY TABLE MASTER_PATIENT_LOOKUP_LOAD AS
        WITH PATIENTS_CTE AS (
            SELECT 
                -- CURRENT_TIMESTAMP() AS QUERY_DISTINGUISHER,
                SOURCE_FILE_LOADED_AT_UTC,
                SOURCE_FILE_DATE_UTC,
                SOURCE_FILE_NAME,
                SOURCE_FILE_UNIQUE_KEY,
                SOURCE_FILE_ROW_NUMBER,
                SOURCE_FILE_RECORD_UNIQUE_KEY,
                MASTER_PATIENT_ID
            FROM GENERAL_HOSPITAL_PATIENTS.PATIENTS
            ),
        ENCOUNTERS_CTE AS (
            SELECT 
                MASTER_PATIENT_ID,
                PATIENT_ENCOUNTER_ID
            FROM GENERAL_HOSPITAL_PATIENTS.ENCOUNTERS
            ),
        SURGICAL_ENCOUNTERS_CTE AS (
            SELECT 
                MASTER_PATIENT_ID,
                SURGERY_ID
            FROM GENERAL_HOSPITAL_PATIENTS.SURGICAL_ENCOUNTERS
            ),
        V_PATIENTS_PRIMARY_CARE_CTE AS (
            SELECT 
                MASTER_PATIENT_ID,
                PCP_ID
            FROM GENERAL_HOSPITAL_PATIENTS.V_PATIENTS_PRIMARY_CARE
            ),
        V_PATIENTS_PRIMARY_CARE_MALEHAM_CTE AS (
            SELECT 
                MASTER_PATIENT_ID,
                PCP_ID
            FROM GENERAL_HOSPITAL_PATIENTS.V_PATIENTS_PRIMARY_CARE_MALEHAM
            ),
        MASTER_PATIENT_LOOKUP_CTE AS(
            SELECT
                p.SOURCE_FILE_LOADED_AT_UTC,
                p.SOURCE_FILE_DATE_UTC,
                p.SOURCE_FILE_NAME,
                p.SOURCE_FILE_UNIQUE_KEY,
                p.SOURCE_FILE_ROW_NUMBER,
                p.SOURCE_FILE_RECORD_UNIQUE_KEY,
                MD5(COALESCE(p.MASTER_PATIENT_ID, 0) || 
                    COALESCE(e.PATIENT_ENCOUNTER_ID, 0) || 
                    COALESCE(se.SURGERY_ID, 0) ||
                    COALESCE(vppc.PCP_ID, 0) ||
                    COALESCE(vppcm.PCP_ID, 0)) AS MASTER_PATIENT_LOOKUP_TABLE_UNIQUE_KEY, 
                p.MASTER_PATIENT_ID AS PATIENTS_MASTER_PATIENT_ID,
                e.PATIENT_ENCOUNTER_ID AS ENCOUNTERS_PATIENT_ENCOUNTER_ID,
                se.SURGERY_ID AS SURGICAL_ENCOUNTERS_SURGERY_ID,
                vppc.PCP_ID AS V_PATIENTS_PRIMARY_CARE_PCP_ID,
                vppcm.PCP_ID AS V_PATIENTS_PRIMARY_CARE_MALEHAM_PCP_ID
            FROM PATIENTS_CTE p
            LEFT JOIN ENCOUNTERS_CTE e 
                ON p.MASTER_PATIENT_ID = e.MASTER_PATIENT_ID
            LEFT JOIN SURGICAL_ENCOUNTERS_CTE se 
                ON p.MASTER_PATIENT_ID = se.MASTER_PATIENT_ID
            LEFT JOIN V_PATIENTS_PRIMARY_CARE_CTE vppc 
                ON p.MASTER_PATIENT_ID = vppc.MASTER_PATIENT_ID
            LEFT JOIN V_PATIENTS_PRIMARY_CARE_MALEHAM_CTE vppcm
                ON p.MASTER_PATIENT_ID = vppcm.MASTER_PATIENT_ID
            )
    SELECT * FROM MASTER_PATIENT_LOOKUP_CTE
    ORDER BY PATIENTS_MASTER_PATIENT_ID;

    MERGE INTO 
        GENERAL_HOSPITAL_PATIENTS.MASTER_PATIENT_LOOKUP t
    USING 
        GENERAL_HOSPITAL_PATIENTS.MASTER_PATIENT_LOOKUP_LOAD s
    ON 
        t.MASTER_PATIENT_LOOKUP_TABLE_UNIQUE_KEY = s.MASTER_PATIENT_LOOKUP_TABLE_UNIQUE_KEY
    WHEN NOT MATCHED THEN
        INSERT (t.SOURCE_FILE_LOADED_AT_UTC,
                t.SOURCE_FILE_DATE_UTC,
                t.SOURCE_FILE_NAME,
                t.SOURCE_FILE_UNIQUE_KEY,
                t.SOURCE_FILE_ROW_NUMBER,
                t.SOURCE_FILE_RECORD_UNIQUE_KEY,
                t.MASTER_PATIENT_LOOKUP_TABLE_UNIQUE_KEY,
                t.PATIENTS_MASTER_PATIENT_ID,
                t.ENCOUNTERS_PATIENT_ENCOUNTER_ID,
                t.SURGICAL_ENCOUNTERS_SURGERY_ID,
                t.V_PATIENTS_PRIMARY_CARE_PCP_ID,
                t.V_PATIENTS_PRIMARY_CARE_MALEHAM_PCP_ID
                )
        VALUES (s.SOURCE_FILE_LOADED_AT_UTC,
                s.SOURCE_FILE_DATE_UTC,
                s.SOURCE_FILE_NAME,
                s.SOURCE_FILE_UNIQUE_KEY,
                s.SOURCE_FILE_ROW_NUMBER,
                s.SOURCE_FILE_RECORD_UNIQUE_KEY,
                s.MASTER_PATIENT_LOOKUP_TABLE_UNIQUE_KEY,
                s.PATIENTS_MASTER_PATIENT_ID,
                s.ENCOUNTERS_PATIENT_ENCOUNTER_ID,
                s.SURGICAL_ENCOUNTERS_SURGERY_ID,
                s.V_PATIENTS_PRIMARY_CARE_PCP_ID,
                s.V_PATIENTS_PRIMARY_CARE_MALEHAM_PCP_ID
                );

    RETURN 'Latest data updated to GENERAL_HOSPITAL_PATIENTS.MASTER_PATIENT_LOOKUP';
                
    EXCEPTION
        WHEN OTHER THEN
            EXECUTE IMMEDIATE create_failover_table;
            RETURN 'Failure during procedure.  Check query history and failover table at: ' || failover_table || '';

END;

$$;

CALL GENERAL_HOSPITAL_PATIENTS.MERGE_DATA_TO_PATIENT_MASTER_TABLE();