-- BELOW IS A SCRIPTED PROCEDURE USED TO DYNAMICALLY GENERATE DML FOR LOADING DATA FROM FILES TO TABLES, USING THE METADATA
-- GENERATED BY INFER SCHEMA TO SET DATATYPES.  THIS MAY ALSO BE DONE AT THE MERGE STEP
-- USE THE SAME SCHEMA_ARG TO SET THE TARGET SCHEMA


--DROP PROCEDURE GENERAL_HOSPITAL_PATIENTS.LOAD_DATA_FROM_FILES(VARCHAR);
CREATE PROCEDURE IF NOT EXISTS GENERAL_HOSPITAL_PATIENTS.LOAD_DATA_FROM_FILES(SCHEMA_ARG VARCHAR)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    schema_ STRING DEFAULT SCHEMA_ARG;
    file_list RESULTSET;
    file_ STRING;  
    table_ STRING;
    copy_into_dml STRING;
    get_column_metadata STRING;
    column_metadata RESULTSET;
    column_ddl STRING;
    copy_into_column_dml STRING;
    column_name STRING;
    column_datatype STRING;
    order_id STRING;

    copy_into_result STRING;
    
    sql_error_message STRING;
    procedure_run_report STRING DEFAULT '';

    --Inner loop exceptions:
    COPY_INTO_EXCEPTION EXCEPTION (-20001, 'ERROR --Copy into failure:  Stopping current iteration. ');
    OTHER_FILE_ITERATION_EXCEPTION EXCEPTION (-20001, 'ERROR --Other-type failure:  Stopping current iteration. ');

    --Outer scope exceptions:
    --None except OTHER

BEGIN
    file_list := (SELECT FILE_NAME AS FILE_NAME
                      FROM (SELECT 
                                METADATA$FILENAME AS FILE_NAME
                            FROM @GENERAL_HOSPITAL_PATIENTS.INBOUND_HEALTHCARE_FILES
                            WHERE 
                                METADATA$FILE_ROW_NUMBER = 1
                            ORDER BY FILE_NAME));
    
    FOR record in file_list DO
    BEGIN        
        file_ := record.file_name;
        table_:= UPPER(REGEXP_SUBSTR(file_, '^(.*)_\\d{14}_UTC.csv.gz', 1, 1, 'e', 1)); 

        procedure_run_report := 'Starting daily ingestion of patient data from file: ' || file_ || '...' || '\n';
        
        copy_into_dml := 'COPY INTO ' || :schema_ || '.' || :table_ || '
                             FROM (SELECT
                                 CONVERT_TIMEZONE(''UTC'', METADATA$START_SCAN_TIME) AS SOURCE_FILE_LOADED_AT_UTC,
                                 TO_DATE(REGEXP_SUBSTR(METADATA$FILENAME, ''_(\\\\d{8})\\\\d{6}_UTC'', 1, 1, ''e'', 1), ''YYYYMMDD'') 
                                    AS SOURCE_FILE_DATE_UTC,
                                 METADATA$FILENAME AS SOURCE_FILE_NAME,
                                 MD5(SOURCE_FILE_LOADED_AT_UTC || SOURCE_FILE_NAME) AS SOURCE_FILE_UNIQUE_KEY,
                                 METADATA$FILE_ROW_NUMBER AS SOURCE_FILE_ROW_NUMBER,          
                                 MD5(SOURCE_FILE_UNIQUE_KEY || SOURCE_FILE_ROW_NUMBER) AS SOURCE_FILE_RECORD_UNIQUE_KEY,' || '\n';
        
        get_column_metadata := 'SELECT 
                                    COLUMN_NAME, TYPE, ORDER_ID
                                FROM TABLE(INFER_SCHEMA(
                                LOCATION => ''@GENERAL_HOSPITAL_PATIENTS.INBOUND_HEALTHCARE_FILES'',
                                FILE_FORMAT => ''GENERAL_HOSPITAL_PATIENTS.INFER_SCHEMA_PATIENT_FILES'',
                                FILES => ''' || :file_ || ''',
                                IGNORE_CASE => FALSE
                                --MAX_FILE_COUNT => <num>
                                --MAX_RECORDS_PER_FILE => <num>
                                ));';
        column_metadata := (EXECUTE IMMEDIATE get_column_metadata);
        
        column_ddl := '';
        copy_into_column_dml := '';
        FOR record in column_metadata DO
            column_name := record.column_name;
            column_datatype := record.type;
            order_id := record.order_id;
            copy_into_column_dml := copy_into_column_dml || '$' || (order_id + '1') || ',' || '\n';
        END FOR;

        copy_into_column_dml := RTRIM(copy_into_column_dml, ',\n');
        copy_into_dml := copy_into_dml || copy_into_column_dml || '\n' || REPEAT('\t ', 7) || 'FROM @GENERAL_HOSPITAL_PATIENTS.INBOUND_HEALTHCARE_FILES)
                                                                                               PATTERN = ''' || :file_ || '''
                                                                                               FILE_FORMAT = ''GENERAL_HOSPITAL_PATIENTS.INGEST_PATIENT_FILES'';';
        EXECUTE IMMEDIATE copy_into_dml;
        copy_into_result := (SELECT ARRAY_TO_STRING(ARRAY_AGG(OBJECT_CONSTRUCT(*)), ', \n\t') FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) t);
        IF (REGEXP_LIKE(copy_into_result, '.*Copy executed with 0 files processed.*')) THEN
            procedure_run_report := procedure_run_report || '\t' || '--Copy into failure.  Result is: ' || copy_into_result || '\n'
                                                         || '\t' || '--Stopping iteration for current file and moving to next.' || '\n';
            RAISE COPY_INTO_EXCEPTION;
        ELSE copy_into_result := (SELECT ARRAY_TO_STRING(ARRAY_AGG(OBJECT_CONSTRUCT(
                                        'file', t."file", 'rows loaded', t."rows_loaded",'status', t."status")), ', \n\t')
                                  FROM TABLE(RESULT_SCAN(LAST_QUERY_ID(-2))) t);
            IF (REGEXP_COUNT(copy_into_result, '"status":') != REGEXP_COUNT(copy_into_result, '"status":"LOADED"')) THEN
                procedure_run_report := procedure_run_report || '\t' || '--Copy into failure.  Result is: ' || copy_into_result || '\n'
                                                             || '\t' || '--Stopping iteration for current file and moving to next.' || '\n';
                RAISE COPY_INTO_EXCEPTION;
            ELSE procedure_run_report := procedure_run_report || '\t' || '--Copy into successful.  Result is: ' || '\n'
                                                              || '\t\t' || copy_into_result || '\n';
            END IF;
        END IF;

        procedure_run_report := procedure_run_report || '...End daily ingestion of patient data for file: ' || file_ || '.' || '\n'
                                                     || '\t' || '--File data ingestion success: TRUE' || '\n';
        INSERT INTO GENERAL_HOSPITAL_PATIENTS.ADMIN_DAILY_INGEST_REPORTS (FILE_NAME, DAILY_INGEST_RESULTS, EXCEPTION_SUMMARY)
        VALUES (:file_, :procedure_run_report, '--No exceptions');

        EXCEPTION 
            WHEN COPY_INTO_EXCEPTION THEN
                sql_error_message := SQLERRM;
                procedure_run_report := procedure_run_report || '...End daily ingestion of patient data for file: ' || file_ || '.' || '\n'
                                                             || '\t' || '--File data ingestion success: FALSE';
                INSERT INTO GENERAL_HOSPITAL_PATIENTS.ADMIN_DAILY_INGEST_REPORTS (FILE_NAME, DAILY_INGEST_RESULTS, EXCEPTION_SUMMARY)
                    VALUES (:file_, :procedure_run_report, :sql_error_message);
                CONTINUE;

            WHEN OTHER_FILE_ITERATION_EXCEPTION THEN
                sql_error_message := SQLERRM;
                procedure_run_report := procedure_run_report || '\t' || '--Other-type failure for file iteration: ' || sql_error_message || '\n'
                                                             || '\t' || '--Stopping iteration for current file and moving to next.' || '\n'
                                                             || '...End daily ingestion of patient data for file: ' || file_ || '.' || '\n'
                                                             || '\t' || '--File data ingestion success: FALSE';
                INSERT INTO GENERAL_HOSPITAL_PATIENTS.ADMIN_DAILY_INGEST_REPORTS (FILE_NAME, DAILY_INGEST_RESULTS, EXCEPTION_SUMMARY)
                    VALUES (:file_, :procedure_run_report, :sql_error_message);
                CONTINUE;
                
    END;                 
    
    END FOR;
                
    RETURN 'SUCCESS -- LOAD_DATA_FROM_FILES() procedure complete.  Check the logs at GENERAL_HOSPITAL_PATIENTS.ADMIN_DAILY_INGEST_REPORTS';

    EXCEPTION
        WHEN OTHER THEN
            sql_error_message := SQLERRM;
            procedure_run_report := procedure_run_report || '\t'   || '--General failure of LOAD_DATA_FROM_FILES() procedure: ' || sql_error_message || '\n'
                                                         || '\t\t' || '--Procedure will terminate.' || '\n\n'
                                                         || '...End daily ingestion of patient data for files.' || '\n'
                                                         || 'Success: FALSE';
            INSERT INTO GENERAL_HOSPITAL_PATIENTS.ADMIN_DAILY_INGEST_REPORTS (FILE_NAME, DAILY_INGEST_RESULTS, EXCEPTION_SUMMARY)
                VALUES (:file_, :procedure_run_report, :sql_error_message);

            RETURN 'ERROR -- LOAD_DATA_FROM_FILES() procedure did not complete.  Check the logs at GENERAL_HOSPITAL_PATIENTS.ADMIN_DAILY_INGEST_REPORTS'
                    || ' for file-specific reports';

END;

$$;